#!/bin/bash
set -e

while getopts "s:a:o:" flag
do
    case "${flag}" in
        s) 
            sourcefile=${OPTARG}
            versionfile=${OPTARG}
            servicename=${OPTARG}
            ;;
        a) 
            appname=${OPTARG}
            ;;
        o) 
            exefile=${OPTARG}
            ;;
    esac
done

[ -z "$versionfile" ] && echo "Version file not located" && exit 1
[ -z "$sourcefile" ] && sourcefile=$sourcefile
[ -z "$exefile" ] && exefile=$exefile
[ -z "$appname" ] && appname=$appname
[ -z "$servicename" ] && servicename=$servicename

echo "App Name: "$appname
echo "Version File: "$versionfile 
echo "Source File: "$sourcefile 
echo "Executable: "$exefile
echo "Service Name: "$servicename

[ ! -f "$versionfile.json" ] && vertool -func create -file $versionfile.json

vertool -file ./$versionfile.json -func inc -section build
vertool -file ./$versionfile.json -func inc -section minor
export APP_VERSION=`vertool -file ./$versionfile.json -func load -section version`
export APP_COPYRIGHT=`vertool -file ./$versionfile.json -func load -section copyright`
export APP_NAME=$appname
export APP_BUILD_DATE=`date`
export APP_BUILD_HOST=`hostname`
export APP_SERVICE_NAME=$servicename

echo "Build for MacOS"
env GOOS=darwin GOARCH=amd64 go build -ldflags "-X 'main.BuildDate=${APP_BUILD_DATE}' -X 'main.BuildHost=${APP_BUILD_HOST}' -X 'main.Version=${APP_VERSION}' -X 'main.Copyright=${APP_COPYRIGHT}' -X 'main.AppName=${APP_NAME}' -X 'main.ServiceName=${APP_SERVICE_NAME}'"  -o $exefile.macos $sourcefile.go
echo "Build for CentOS"
env GOOS=linux GOARCH=amd64 go build -ldflags "-X 'main.BuildDate=${APP_BUILD_DATE}' -X 'main.BuildHost=${APP_BUILD_HOST}' -X 'main.Version=${APP_VERSION}' -X 'main.Copyright=${APP_COPYRIGHT}' -X 'main.AppName=${APP_NAME}' -X 'main.ServiceName=${APP_SERVICE_NAME}'"  -o $exefile.centos $sourcefile.go
echo "Build for Alpine"
env GOOS=linux GOARCH=386 go build -ldflags "-X 'main.BuildDate=${APP_BUILD_DATE}' -X 'main.BuildHost=${APP_BUILD_HOST}' -X 'main.Version=${APP_VERSION}' -X 'main.Copyright=${APP_COPYRIGHT}' -X 'main.AppName=${APP_NAME}' -X 'main.ServiceName=${APP_SERVICE_NAME}'"  -o $exefile.alpine $sourcefile.go
echo "Build for Windows"
env GOOS=windows GOARCH=amd64 go build -ldflags "-X 'main.BuildDate=${APP_BUILD_DATE}' -X 'main.BuildHost=${APP_BUILD_HOST}' -X 'main.Version=${APP_VERSION}' -X 'main.Copyright=${APP_COPYRIGHT}' -X 'main.AppName=${APP_NAME}' -X 'main.ServiceName=${APP_SERVICE_NAME}'"  -o $exefile.exe $sourcefile.go

echo ""
echo "APP_NAME="$APP_NAME
echo "APP_COPYRIGHT="$APP_COPYRIGHT
echo "APP_VERSION="$APP_VERSION
echo "Completed $appname compilation. $exefile ready to run...service $servicename"
echo ""
